/**
 * The email palette, derived from `packages/tokens/src/tokens.css` — the single source of
 * truth for every colour, radius and font in the product. Email clients read no custom
 * properties, so the values are resolved here (a `var()` chain is followed to its literal)
 * and written into `src/generated/palette.ts` by `generate-palette.mjs`. Nothing in
 * `packages/mail/src` outside that generated file may carry a literal.
 *
 * Light values come from `:root`; dark values from the `[data-theme="dark"]` swap (the
 * `prefers-color-scheme` block is identical by test, `tokens.test.ts`). A token the dark
 * block does not redeclare keeps its light value, exactly as the cascade would.
 */

/** `--name: value` pairs of the first block whose selector matches, comments stripped. */
function declarations(css, selector) {
  const m = new RegExp(`${selector.source}\\s*\\{([^}]*)\\}`).exec(css);
  if (m === null) throw new Error(`tokens.css: no block for ${selector.source}`);
  const out = new Map();
  for (const d of m[1].split(';')) {
    const i = d.indexOf(':');
    if (i < 0) continue;
    const name = d.slice(0, i).trim();
    const value = d.slice(i + 1).trim();
    if (name.startsWith('--') && value !== '') out.set(name, value);
  }
  return out;
}

/** Follow `var(--x)` to a literal within `scope`, then `base`. */
function resolve(name, scope, base) {
  let value = scope.get(name) ?? base.get(name);
  if (value === undefined) throw new Error(`tokens.css: no token ${name}`);
  for (let hops = 0; hops < 10; hops++) {
    const ref = /^var\((--[\w-]+)\)$/.exec(value);
    if (ref === null) return value;
    value = scope.get(ref[1]) ?? base.get(ref[1]);
    if (value === undefined) throw new Error(`tokens.css: no token ${ref[1]} (via ${name})`);
  }
  throw new Error(`tokens.css: ${name} does not resolve to a literal`);
}

/**
 * Which token each palette field reads. The accent is the live amber — on the light
 * surface the 700 weight (`--selection-ring`), on the dark surface the lifted 300 weight the
 * theme already uses for `--warning` and the dark selection ring — so the code reads at
 * ≥ 4.5:1 on both. The button is the primary action fill with its `--ink` on brand.
 */
const FIELDS = {
  surface: '--surface',
  surfaceSunken: '--surface-sunken',
  border: '--border',
  ink: '--ink',
  inkMuted: '--ink-muted',
  link: '--link',
  actionBg: '--action-primary-bg',
  actionFg: '--action-primary-fg',
  accent: '--selection-ring',
  accentSubtle: '--tint-amber-soft',
};

export function derivePalette(css) {
  const stripped = css.replace(/\/\*[\s\S]*?\*\//g, '');
  const light = declarations(stripped, /:root/);
  const dark = declarations(stripped, /\[data-theme="dark"\]/);
  const pick = (scope) =>
    Object.fromEntries(
      Object.entries(FIELDS).map(([field, token]) => [field, resolve(token, scope, light)]),
    );
  const colors = { light: pick(light), dark: pick(dark) };
  // color-mix() has no email-client support; the dark code box takes the sunken surface.
  if (colors.dark.accentSubtle.startsWith('color-mix(')) {
    colors.dark.accentSubtle = colors.dark.surfaceSunken;
  }
  return {
    colors,
    fontUi: resolve('--font-ui', light, light),
    fontMono: resolve('--font-mono', light, light),
    radiusMd: resolve('--radius-md', light, light),
    radiusLg: resolve('--radius-lg', light, light),
  };
}

/** The TypeScript module `src/generated/palette.ts`, byte for byte. */
export function renderPaletteModule(palette) {
  const scheme = (c) =>
    Object.entries(c)
      .map(([k, v]) => `    ${k}: '${v}',`)
      .join('\n');
  return [
    '// Generated by `npm run generate -w packages/mail` from packages/tokens/src/tokens.css.',
    '// Do not edit; `palette.test.ts` fails when this file drifts from the tokens.',
    'export const palette = {',
    '  colors: {',
    '    light: {',
    scheme(palette.colors.light).replace(/^/gm, '  '),
    '    },',
    '    dark: {',
    scheme(palette.colors.dark).replace(/^/gm, '  '),
    '    },',
    '  },',
    // Broken the way prettier breaks it (the stack is longer than printWidth).
    '  fontUi:',
    `    "${palette.fontUi.replace(/"/g, '\\"')}",`,
    `  fontMono: "${palette.fontMono.replace(/"/g, '\\"')}",`,
    `  radiusMd: '${palette.radiusMd}',`,
    `  radiusLg: '${palette.radiusLg}',`,
    '} as const;',
    '',
    'export type Palette = typeof palette;',
    "export type ColorScheme = keyof Palette['colors'];",
    '',
  ].join('\n');
}
