/**
 * Context graphs (PRD §19; GRAPH-01..11): graph objects in the document,
 * the live derivation dimensions → parameters → contexts, the ring and
 * coverage layouts, and the pair mutations. Framework-free; the ring layout
 * and derivation are pure and property-tested.
 *
 * The graph slot's readers (`GraphRecord`, `graphById`, `graphsOnSheet`,
 * `graphsInPair`, `GraphSlice`) live with the rest of the document schema in
 * `doc/schema.ts`.
 */
export {
  coverageLabel,
  deriveGraph,
  distinctValueCount,
  GREEK_SYMBOLS,
  normaliseValue,
  parameterKey,
  resolveDimensionIds,
  symbolFor,
  TUPLE_SEPARATOR,
  tupleKeyOf,
  UNBOUND_MARK,
  type GraphContext,
  type GraphDerivation,
  type GraphDimension,
  type GraphInput,
  type GraphInputColumn,
  type GraphInputRow,
  type GraphParameter,
} from './derive.js';
export {
  cellWriteBack,
  coverageMatrix,
  resolveSlice,
  withAxis,
  withPin,
  type CoverageCell,
  type CoverageMatrix,
  type ResolvedPin,
  type ResolvedSlice,
} from './coverage.js';
export {
  adjacencyOf,
  ARC_GAP,
  DENSE_CONTEXTS,
  DOT_RADIUS,
  DOT_RADIUS_EMPHASISED,
  NO_ADJACENCY,
  NODE_RADIUS,
  NODE_RADIUS_DENSE,
  orbitsFor,
  polar,
  RING_CENTRE,
  RING_MARGIN,
  RING_RADIUS,
  RING_SIZE,
  ringLayout,
  spokesFor,
  truncateLabel,
  type GraphAdjacency,
  type GraphEmphasis,
  type RingArc,
  type RingDot,
  type RingLayout,
  type RingNode,
  type RingPoint,
  type RingSpoke,
  type TextAnchor,
} from './ring.js';
export { eligibleColumns, graphInputOf, type GraphValueReader } from './input.js';
export {
  appendRowWithValues,
  bindGraphPair,
  bindShapedTable,
  createChildSheet,
  createGraphPair,
  createShapedTable,
  createShapedTableWithGraph,
  DEFAULT_DIMENSION_COUNT,
  defaultDimensions,
  defaultPairOrigin,
  pairOf,
  removeGraphPair,
  setGraphDimensions,
  setGraphPosition,
  setGraphSize,
  setGraphSlice,
  SHAPED_TABLE_COLUMNS,
  SHAPED_TABLE_ROWS,
  toggleGraphDimension,
  type ChildSheetOptions,
  type CreateGraphPairOptions,
  type GraphPair,
  type ShapedTableOptions,
} from './mutations.js';
