import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { describe, expect, it } from 'vitest';

/**
 * The committed brand assets (DESIGN-SYSTEM-DIGEST §3), generated by
 * `scripts/brand-assets.mjs`. Checked by their headers, not by pixels.
 */
const pub = (name: string) => readFileSync(resolve(__dirname, '../public', name));
const html = readFileSync(resolve(__dirname, '../index.html'), 'utf8');
const manifest = JSON.parse(pub('site.webmanifest').toString('utf8')) as {
  theme_color: string;
  background_color: string;
  icons: { src: string; sizes: string; type: string; purpose: string }[];
};

/** Width × height from a PNG IHDR chunk. */
function pngSize(buf: Buffer): [number, number] {
  expect(buf.subarray(0, 8)).toEqual(Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]));
  return [buf.readUInt32BE(16), buf.readUInt32BE(20)];
}

describe('brand assets', () => {
  it('DS §3 the raster icons exist at the sizes the design system lists', () => {
    expect(pngSize(pub('icon-192.png'))).toEqual([192, 192]);
    expect(pngSize(pub('icon-512.png'))).toEqual([512, 512]);
    expect(pngSize(pub('icon-maskable-512.png'))).toEqual([512, 512]);
    expect(pngSize(pub('apple-touch-icon.png'))).toEqual([180, 180]);
    expect(pngSize(pub('og-card.png'))).toEqual([1200, 630]);
  });

  it('DS §3 favicon.ico holds 16, 32 and 48 px frames', () => {
    const ico = pub('favicon.ico');
    expect(ico.readUInt16LE(0)).toBe(0);
    expect(ico.readUInt16LE(2)).toBe(1);
    const count = ico.readUInt16LE(4);
    const sizes = Array.from({ length: count }, (_, i) => ico.readUInt8(6 + i * 16));
    expect(sizes).toEqual([16, 32, 48]);
    for (let i = 0; i < count; i++) {
      const offset = ico.readUInt32LE(6 + i * 16 + 12);
      const length = ico.readUInt32LE(6 + i * 16 + 8);
      expect(pngSize(ico.subarray(offset, offset + length))[0]).toBe(sizes[i]);
    }
  });

  it('DS §3 the pinned-tab mask is a monochrome SVG of the 16 px mark', () => {
    const svg = pub('safari-pinned-tab.svg').toString('utf8');
    expect(svg).toMatch(/^<svg /);
    expect(svg).toContain('viewBox="0 0 40 40"');
    expect(svg).toContain('<circle cx="25" cy="25" r="7"');
    expect(svg).not.toMatch(/currentColor|<path/);
  });

  it('DS §2 §9 the manifest theme_color is the light surface and the icon set includes the maskable 512', () => {
    expect(manifest.theme_color).toBe('#ffffff');
    expect(manifest.background_color).toBe('#ffffff');
    expect(manifest.icons.map((i) => `${i.src} ${i.sizes} ${i.purpose}`)).toEqual([
      '/favicon.svg any any',
      '/icon-192.png 192x192 any',
      '/icon-512.png 512x512 any',
      '/icon-maskable-512.png 512x512 maskable',
    ]);
  });

  it('DS §2 index.html links every asset and its theme-color follows the painted surface per scheme', () => {
    expect(html).toContain('<link rel="icon" href="/favicon.svg" type="image/svg+xml" />');
    expect(html).toContain('<link rel="icon" href="/favicon.ico" sizes="16x16 32x32 48x48" />');
    expect(html).toContain('<link rel="apple-touch-icon" href="/apple-touch-icon.png"');
    expect(html).toContain(
      '<link rel="mask-icon" href="/safari-pinned-tab.svg" color="#14532d" />',
    );
    expect(html).toContain('<meta property="og:image" content="https://gede.work/og-card.png" />');
    expect(html).toMatch(
      /<meta name="theme-color" content="#ffffff" media="\(prefers-color-scheme: light\)" \/>/,
    );
    expect(html).toMatch(
      /<meta name="theme-color" content="#0f1a15" media="\(prefers-color-scheme: dark\)" \/>/,
    );
  });
});
