// The one-shot migration runner's AWS-specific adapter (issue 045). Invoked
// as a CDK custom resource's onEvent Lambda on every `cdk deploy` (via
// migration-stack.ts's `cr.Provider`) — connects to the deployed RDS Postgres
// (VPC-attached; the Data stack's isolated subnets have no public route, so
// this Lambda must run inside the VPC — docs/DEPLOYMENT.md §9) using
// credentials fetched from Secrets Manager, and applies `applyMigrations.ts`'s
// pure logic against the migration files bundled alongside this handler
// (copied verbatim from `src/db/migrations/*.sql` at build time — see
// `migration-stack.ts`'s `NodejsFunction` `afterBundling` command hook; never
// forked).
//
// Mirrors `src/server/writeApi/albAdapter.ts`'s "thin AWS adapter, pure core"
// split (ADR-0010) — this file is the ONLY place here that touches AWS event
// shapes, Secrets Manager, and a live `pg.Client`; `applyMigrations.ts` is
// fully unit-tested without either (see `deploy/cdk/test/migration-runner.test.ts`).
import { readFileSync } from 'node:fs';
import * as path from 'node:path';
import { GetSecretValueCommand, SecretsManagerClient } from '@aws-sdk/client-secrets-manager';
import { Client } from 'pg';
import { applyMigrations } from './applyMigrations';

// Minimal local shape of the CloudFormation custom-resource event/response —
// deliberately not pulling in `@types/aws-lambda`'s `CloudFormationCustomResource*`
// types (and a new deploy/cdk devDependency) for a handler this repo's tests
// never type-check directly, mirroring how `albAdapter.ts` is "reviewed, not
// exercised by any test" (see that file's header comment).
interface CustomResourceEvent {
  readonly RequestType: 'Create' | 'Update' | 'Delete';
}

interface CustomResourceResponse {
  readonly PhysicalResourceId: string;
  readonly Data?: Record<string, string>;
}

interface DbSecret {
  readonly username: string;
  readonly password: string;
}

// Stable across every Create/Update — this is one logical resource (the
// applied-migrations state of the RDS instance), never replaced.
const PHYSICAL_RESOURCE_ID = 'gede-migration-runner';

// Copied verbatim alongside this handler at bundle time (see
// migration-stack.ts's NodejsFunction `bundling.commandHooks.afterBundling`).
const MIGRATIONS_DIR = path.join(__dirname, 'migrations');

export async function handler(event: CustomResourceEvent): Promise<CustomResourceResponse> {
  if (event.RequestType === 'Delete') {
    // Migrations are never rolled back by tearing down the stack — dropping
    // tables on `cdk destroy` would be a data-loss footgun, not "idempotent
    // re-run". A no-op Delete matches RemovalPolicy.SNAPSHOT on the RDS
    // instance itself (data-stack.ts): the schema/data outlive stack teardown.
    return { PhysicalResourceId: PHYSICAL_RESOURCE_ID };
  }

  const secretArn = requireEnv('DATABASE_SECRET_ARN');
  const endpoint = requireEnv('DATABASE_ENDPOINT');
  const database = process.env.DATABASE_NAME ?? 'gede';

  const secretsClient = new SecretsManagerClient({});
  const secretResponse = await secretsClient.send(new GetSecretValueCommand({ SecretId: secretArn }));
  const secret = JSON.parse(secretResponse.SecretString ?? '{}') as Partial<DbSecret>;
  if (!secret.username || !secret.password) {
    throw new Error('DATABASE_SECRET_ARN did not resolve to a { username, password } secret');
  }

  // Connects as the master credential (gede_admin, generated by data-stack.ts)
  // — the same role src/db/migrations/0008_workspaces_rls.sql expects to
  // apply the migrations AS (table owner, so RLS is inert for THIS
  // connection by Postgres' owner-exemption — see that file's header). The
  // runner's job is to CREATE the `app_user` role + policies, not to connect
  // as it; the write-path Lambda (046, api-stack.ts) is what connects as
  // `app_user`.
  const client = new Client({
    host: endpoint,
    port: 5432,
    database,
    user: secret.username,
    password: secret.password,
    // Verify the RDS server cert against Amazon's RDS CA bundle, copied into
    // this Lambda's bundle at build time (migration-stack.ts's afterBundling
    // hook, alongside the migrations/ dir). Without a pinned CA, node's default
    // trust store rejects RDS's AWS-managed CA as "self-signed certificate in
    // certificate chain" and the deploy fails.
    ssl: {
      ca: readFileSync(path.join(__dirname, 'rds-global-bundle.pem'), 'utf8'),
      rejectUnauthorized: true,
    },
  });
  await client.connect();
  try {
    const result = await applyMigrations(client, MIGRATIONS_DIR);
    // CloudWatch Logs is the only "\dt"-equivalent diagnostic available
    // post-deploy without a bastion (issue 045 test-first plan item 4); this
    // log line, plus the custom resource's returned Data (surfaced via
    // migration-stack.ts's CfnOutput), is the deploy smoke signal.
    // eslint-disable-next-line no-console
    console.log(
      `migration-runner: applied ${result.applied.length} migration(s) (${result.applied.join(', ') || 'none'}); ` +
        `skipped ${result.skipped.length} already-applied.`,
    );
    return {
      PhysicalResourceId: PHYSICAL_RESOURCE_ID,
      Data: {
        Applied: result.applied.join(','),
        AppliedCount: String(result.applied.length),
        SkippedCount: String(result.skipped.length),
      },
    };
  } finally {
    await client.end();
  }
}

function requireEnv(name: string): string {
  const value = process.env[name];
  if (!value) throw new Error(`Missing required environment variable: ${name}`);
  return value;
}
