import * as crypto from 'node:crypto';
import * as fs from 'node:fs';
import * as path from 'node:path';
import { Stack, StackProps, CfnOutput, CustomResource, Duration } from 'aws-cdk-lib';
import * as ec2 from 'aws-cdk-lib/aws-ec2';
import * as lambda from 'aws-cdk-lib/aws-lambda';
import * as nodejs from 'aws-cdk-lib/aws-lambda-nodejs';
import * as cr from 'aws-cdk-lib/custom-resources';
import * as secretsmanager from 'aws-cdk-lib/aws-secretsmanager';
import { Construct } from 'constructs';

export interface MigrationStackProps extends StackProps {
  /** The Network stack's VPC — the runner must reach the isolated-subnet RDS (issue 045; DEPLOYMENT.md §9). */
  vpc: ec2.IVpc;
  /**
   * The Data stack's RDS security group. This stack adds the ONE ingress
   * rule it needs (this runner's SG -> 5432) as a forward reference, the
   * same one-directional pattern api-stack.ts uses for its own compute/
   * write-Lambda SGs (see that file's class doc for the circular-dependency
   * rationale — it applies here identically).
   */
  databaseSecurityGroup: ec2.ISecurityGroup;
  /** The Data stack's generated RDS credentials secret — the runner connects as this (master) role to create app_user + apply RLS/DDL. */
  databaseSecret: secretsmanager.ISecret;
  /** The Data stack's RDS endpoint address. */
  databaseEndpoint: string;
}

/** The real, single source of migration SQL — never forked (issue 045 scope). */
const MIGRATIONS_SOURCE_DIR = path.resolve(__dirname, '..', '..', '..', 'src', 'db', 'migrations');
// Amazon RDS global CA bundle (deploy/cdk/lib/rds-global-bundle.pem), copied
// into both this stack's runner Lambda and api-stack.ts's write Lambda so each
// can verify the RDS server cert. One shared source file, no duplication.
const RDS_CA_SOURCE = path.resolve(__dirname, 'rds-global-bundle.pem');

/**
 * `Gede-Test-Migrations` — issue 045's one-shot, idempotent migration
 * runner: the missing piece that makes the deployed RDS (`Gede-Test-Data`)
 * actually HAVE a schema. Before this stack, the RDS was provisioned but
 * empty — `src/db/migrate.ts` only ever runs against in-browser PGlite, and
 * `deploy/migration-parity/check-migrations.sh` only ever proves parity
 * against a throwaway CI container. Neither ever touches the deployed
 * instance.
 *
 * Shape (cheapest option per the issue's own ranking): a VPC-attached
 * `NodejsFunction`, bundled offline via esbuild (no Docker — mirrors
 * api-stack.ts's write-path Lambda, issue 046/041), fronted by a CDK
 * `custom-resources.Provider` so it runs as a `CustomResource` on every
 * `cdk deploy` — `$0` idle, no always-on task (ADR-0010's serverless
 * posture), same as the issue-043 write-path Lambda.
 *
 * Idempotent + content-addressed trigger (issue 045 design brief, issue 041
 * lesson): the `CustomResource`'s `MigrationSetHash` property is a SHA-256 of
 * every `src/db/migrations/*.sql` file's name + content, computed at synth
 * time. CloudFormation only re-invokes the runner (an Update) when that hash
 * actually changes — i.e. when a migration file is added or edited — never
 * on an unrelated deploy, and never based on machine/time (deterministic
 * across every machine that has the same checked-in `.sql` files). The
 * runner itself (`migration-runner/applyMigrations.ts`) is independently
 * idempotent regardless: re-running it against an already-migrated database
 * is a safe no-op via the `__migrations` ledger table (same ledger shape as
 * `src/db/migrate.ts`'s PGlite runner).
 *
 * Never forks the SQL: `bundling.commandHooks.afterBundling` copies
 * `src/db/migrations/*.sql` verbatim alongside the bundled handler — the
 * exact same files `src/db/migrate.ts` (PGlite) and
 * `deploy/migration-parity/check-migrations.sh` (CI parity) already apply.
 *
 * Deploy-order note (see also api-stack.ts's write-path Lambda doc): the
 * write-path Lambda (issue 046) assumes this stack's migrations have already
 * applied the schema by the time it receives its first write. That's a
 * deploy-ORDER concern (the CI pipeline deploys stacks 045 -> 046 -> 047),
 * not a synth-time one — this stack deliberately has no CDK
 * `addDependency`/consumer relationship with the Api stack (see
 * build-app.ts's comment), since enforcing it at the CloudFormation level
 * would add incidental coupling with no synth-time meaning.
 *
 * RLS note (issue 034/045): migration `0008_workspaces_rls.sql` both enables
 * RLS policies AND creates the least-privileged `app_user` role those
 * policies actually gate. This runner connects as the RDS master credential
 * (`gede_admin`, generated by data-stack.ts) — the same role that OWNS every
 * table it creates, so Postgres' owner-exemption makes RLS a no-op for this
 * connection (matching 0008's own header comment on why this is
 * "permissive on PGlite, enforcing on Postgres" with zero dialect fork). The
 * write-path Lambda (046) is what connects as `app_user`, where RLS is fully
 * enforced.
 */
export class MigrationStack extends Stack {
  public readonly runnerSecurityGroup: ec2.SecurityGroup;
  public readonly runnerFunction: nodejs.NodejsFunction;
  public readonly resource: CustomResource;

  constructor(scope: Construct, id: string, props: MigrationStackProps) {
    super(scope, id, props);

    this.runnerSecurityGroup = new ec2.SecurityGroup(this, 'MigrationRunnerSecurityGroup', {
      vpc: props.vpc,
      description:
        `${id} one-shot migration runner Lambda (issue 045) - egress to Postgres (5432) only; ` +
        'invoked once per deploy via a CDK custom resource, never left running.',
      allowAllOutbound: true,
    });

    new ec2.CfnSecurityGroupIngress(this, 'AllowMigrationRunnerToPostgres', {
      groupId: props.databaseSecurityGroup.securityGroupId,
      ipProtocol: 'tcp',
      fromPort: 5432,
      toPort: 5432,
      sourceSecurityGroupId: this.runnerSecurityGroup.securityGroupId,
      description:
        'Migration runner Lambda (issue 045) to Postgres 5432 - a third, independent ingress rule on the ' +
        'Data security group (alongside the Fargate compute and write-path Lambda SG rules in api-stack.ts); ' +
        'still never 0.0.0.0/0.',
    });

    // Both this stack's NodejsFunction and api-stack.ts's write-path Lambda
    // bundle from source that lives OUTSIDE deploy/cdk (this directory, and
    // src/server/writeApi respectively) but depend on the REPO ROOT's
    // node_modules (pg, @aws-sdk/client-secrets-manager) - pin the lock file
    // explicitly rather than let NodejsFunction's default "nearest lock file"
    // search find deploy/cdk's own (unrelated) package-lock.json first.
    const rootLockFile = path.resolve(__dirname, '..', '..', '..', 'package-lock.json');

    this.runnerFunction = new nodejs.NodejsFunction(this, 'MigrationRunnerFunction', {
      description:
        `${id} one-shot migration runner (issue 045) - applies src/db/migrations/*.sql in filename order ` +
        'to the RDS via a CDK custom resource; idempotent, skips already-applied files.',
      entry: path.join(__dirname, 'migration-runner', 'handler.ts'),
      handler: 'handler',
      runtime: lambda.Runtime.NODEJS_20_X,
      memorySize: 256,
      // Twelve migrations today; generous headroom for the history to grow
      // without needing a follow-up bump (this is a one-shot Create/Update
      // invocation, not a hot path - cost is invocation count, not duration).
      timeout: Duration.minutes(5),
      vpc: props.vpc,
      vpcSubnets: { subnetType: ec2.SubnetType.PRIVATE_WITH_EGRESS },
      securityGroups: [this.runnerSecurityGroup],
      depsLockFilePath: rootLockFile,
      environment: {
        DATABASE_SECRET_ARN: props.databaseSecret.secretArn,
        DATABASE_ENDPOINT: props.databaseEndpoint,
      },
      bundling: {
        minify: true,
        sourceMap: false,
        target: 'node20',
        // Offline synth (issue 041 lesson): esbuild is a deploy/cdk
        // devDependency (issue 043) specifically so this never needs Docker.
        forceDockerBundling: false,
        commandHooks: {
          beforeBundling: () => [],
          beforeInstall: () => [],
          afterBundling: (_inputDir: string, outputDir: string) => [
            // Copy the SAME src/db/migrations/*.sql files src/db/migrate.ts
            // (PGlite) and check-migrations.sh (CI parity) already apply -
            // never fork the SQL (issue 045 scope). Runs on the host (no
            // Docker), so this absolute host path is valid.
            `mkdir -p "${outputDir}/migrations"`,
            `cp "${MIGRATIONS_SOURCE_DIR}"/*.sql "${outputDir}/migrations/"`,
            // Amazon RDS CA bundle so handler.ts can verify the RDS server
            // cert (ssl.rejectUnauthorized:true) instead of failing on the
            // AWS-managed CA. Shared source file with api-stack.ts's write Lambda.
            `cp "${RDS_CA_SOURCE}" "${outputDir}/rds-global-bundle.pem"`,
          ],
        },
      },
    });
    props.databaseSecret.grantRead(this.runnerFunction);

    const provider = new cr.Provider(this, 'MigrationRunnerProvider', {
      onEventHandler: this.runnerFunction,
    });

    // Content-addressed, not machine/time-based (issue 041 lesson): this
    // property changes if and only if the migration file SET or CONTENTS
    // change, so CloudFormation only re-invokes the runner (an Update) when
    // there's actually new SQL to apply - the same files hash identically on
    // every machine, unlike e.g. a build timestamp.
    const migrationFiles = fs
      .readdirSync(MIGRATIONS_SOURCE_DIR)
      .filter((f) => f.endsWith('.sql'))
      .sort();
    const migrationsHash = crypto.createHash('sha256');
    for (const file of migrationFiles) {
      migrationsHash.update(file);
      migrationsHash.update(fs.readFileSync(path.join(MIGRATIONS_SOURCE_DIR, file)));
    }

    this.resource = new CustomResource(this, 'MigrationRunnerResource', {
      serviceToken: provider.serviceToken,
      properties: {
        MigrationSetHash: migrationsHash.digest('hex'),
        MigrationFileCount: migrationFiles.length,
      },
    });

    new CfnOutput(this, 'MigrationsApplied', {
      value: this.resource.getAttString('Applied'),
      description:
        'Comma-separated migration filenames applied by the MOST RECENT run (empty if this deploy had ' +
        'nothing new) - issue 045 test-first plan item 4, the deploy-smoke signal.',
    });
  }
}
